---
- name: systemd daemon-reload
  systemd: name=wildfly.service daemon_reload=yes state=restarted
  become: true
  tags: superuser
- name:  service reload
  service: name=wildfly state=restarted
  become: true
  tags: superuser
